name: continuous-integration
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

  push:
    branches:
      - main

concurrency: ci-${{ github.ref }}

jobs:
  ci:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        if: ${{ github.event_name }} != 'push'
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Cache conda
        uses: actions/cache@v2
        env:
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('code/train/environment.yaml') }}

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: conda-env
          channel-priority: strict
          environment-file: code/train/environment.yaml
          use-only-tar-bz2: true

      - name: Style check
        uses: pre-commit/action@v2.0.3

      - name: Run unittests
        run: |
          python -m unittest discover 
