# Actions train a model on Azure Machine Learning
name: aml-train
on:
  workflow_dispatch:
    inputs:
      repository:
        description: "The repository from which the slash command was dispatched"
        required: false
      comment-id:
        description: "The comment-id of the slash command"
        required: false
      issue-number:
        description: "The issue number from which the slash command was created"
        required: false
      az-workspace:
        description: 'Azure workspace'
        required: false
        default: "lc-onboarding"
      az-resource-group:
        description: "Azure resource group"
        required: false
        default: "lc-test"
      kernel:
        description: "Kernel type for SVM model"
        required: false
        type: choice
        default: "linear"
        options:
          - "linear"
          - "rbf"
          - "sigmoid"
          - "poly"
      penalty:
        description: "Penalty for SVM model"
        required: false
        default: "0.1"

concurrency: train-refs/pull/${{ github.event.inputs.issue-number }}/head

jobs:
  train:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repository
      id: checkout_repository
      uses: actions/checkout@v3
        
    - name: Setup
      uses: ./.github/actions/env_setup
      with:
        event_name: ${{ github.event_name }}
        issue_number: ${{ github.event.inputs.issue-number }}
        az_workspace: ${{ github.event.inputs.az-workspace || 'lc-onboarding' }}
        az_resource_group: ${{ github.event.inputs.az-resource-group || 'lc-test' }}
        az_secret: ${{ secrets.AZURE_LOGIN }}

    - name: Setting env var for train parameter file
      run: |
        deploy_env=${{ github.environment.name }}
        case $deploy_env in
          Production | Staging)
            param_file="prd_params.json"
            echo "${deploy_env}, using prd_params.json"
            ;;
          *)
            param_file="dev_params.json"
            echo "${deploy_env}, using dev_params.json"
            ;;
        export "PARAM_FILE=$param_file" >> $GITHUB_ENV

    - name: Create URL to the run output
      id: vars
      run: echo ::set-output name=run-url::https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID

    - name: Create comment for training url
      if: ${{ github.event.inputs.issue-number != '' }}
      uses: peter-evans/create-or-update-comment@v2
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        issue-number: ${{ github.event.inputs.issue-number }}
        body: |
           Submitting train run, [Click here for more details](${{ steps.vars.outputs.run-url }})

    - name: Submit training run
      id: submit_train
      run: |
        echo "$PARAM_FILE"
        res=$(az ml run submit-script \
        --conda-dependencies ./code/train/environment.yaml \
        --experiment-name iris_experiment \
        --source-directory ./code/train \
        --ct cpu-cluster train.py --kernel ${KERNEL} --penalty ${PENALTY})
        echo ::set-output name=response::$res
      env:
        KERNEL: ${{ github.event.inputs.kernel || 'linear' }}
        PENALTY: ${{ github.event.inputs.penalty || '0.1' }}
        MODEL_NAME: ${{ github.event.inputs.model-name || 'iris_model' }}

    - name: Create comment for training response
      if: ${{ github.event.inputs.issue-number != '' }}
      uses: peter-evans/create-or-update-comment@v2
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        issue-number: ${{ github.event.inputs.issue-number }}
        body: |
          ${{ steps.submit_train.outputs.response }}
